name: CI_Frontend

on: 
  pull_request: 

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Packages
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Build project
      run: npm run build
    - name: Run Tests
      uses: cypress-io/github-action@v1
      with: 
        spec: cypress/integration/spec.js
        wait-on: https://ask-edd-project-dev.vercel.app/
        record: true

